name: apatheia
description: A hyper-minimalist focus app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Ειδοποιήσεις & Ώρα
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  # Αποθήκευση
  shared_preferences: ^2.2.2
  # Design & Animations
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Το πακέτο για τα εικονίδια
  flutter_launcher_icons: ^0.13.1

# Ρυθμίσεις για τα εικονίδια
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" 
  adaptive_icon_background: "#bc955c" 
  adaptive_icon_foreground: "assets/ic_notif.png" 

flutter:
  uses-material-design: true
  
  # Δήλωση των assets
  assets:
    - assets/logo.png
    - assets/ic_notif.png